### ISSUE TITLE
Support for RX-SD01B Format

### ISSUE THREAD

**Issue by Stalkk** [cratu/YX-SD01A#1]
Hi,

thank you for your project!
I just got the new controller, RX-SD01B. Probably new version of YX-SD01A. Unfortunately your program can't read its files.  Could you take a look on it?  Could be just the header differences or something like that. 

Thanks.

[LED_Controller_RX-SD01B_SDCard.zip](https://github.com/cratu/YX-SD01A/files/2604414/LED_Controller_RX-SD01B_SDCard.zip)

**Comment by cratu** [comment]
Hello.
Format is generaly the same, but changed color encoding can you please describe 4th programm, what happend? I think stripe are colored in one color, which one?

**Comment by Stalkk** [comment]
Basically it's a running light program with changing color. first purple, then blue, then turquoise, green and red. The distance between two lights is about 10 LEDs. If you want i can upload video.  And is got more programs on SD - about 20. You can find it attached:
[LED_SD.zip](https://github.com/cratu/YX-SD01A/files/2613350/LED_SD.zip)

**Comment by Stalkk** [comment]
Hi,
do you need the video?

**Comment by cratu** [comment]
Sorry for long timeout. I hav no a lot of free time. Yes video can help me.
Please leve on flash just one file (4_1.bin) and make the video. And
another one with other program, does not matter which one(just say me name
of file).

I'll look what I can do.

ср, 12 дек. 2018 г. в 10:44, Stalkk <notifications@github.com>:

**Comment by Stalkk** [comment]
thanx. 

Here is it: 
https://youtu.be/61V_I1Hi2lY

first running 4_1.bin and then 17_1.bin.

**Comment by cratu** [comment]
Hello. I finally watch the video. Are you shure that you show me 4 and 17 programs?
When I watch files in HEX I see in 4_1 just one color, the stripe must be in one color. I need to know which.

**Comment by cratu** [comment]
the 4_1 is:
Header: 

> 00 18 98 13 06 14 55 55 55 55 55 55 55 55 55 55
> ...
> 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55


and lamp color codes:


> F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0
> F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0 F0


all the same. I guess this is white

**Comment by cratu** [comment]
I've found the solution. Check lastest version.

**Comment by Stalkk** [comment]
Thank you, now i am not really sure - seems this board can even read deleted files. So probably it was deleted 1_1.bin and this is b/w. I'll check it later, but now i can't play any file anymore. Even after SD card format and restore default files.

**Comment by cratu** [comment]
File manipulations work correctly for SD01A. I do this many times.
You can ask seller from Ali how to restore SD card.
